import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { HeaderAuthArea } from "@/components/HeaderAuthArea";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <div className="min-h-dvh flex flex-col">
            <header className="w-full border-b p-4 flex items-center justify-between">
              <div className="font-semibold">Nested Comments</div>
              <HeaderAuthArea />
            </header>
            <main className="flex-1 p-4">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

// moved to client component components/HeaderAuthArea.tsx
